### ISSUE TITLE
Explicit nil return value in function declaration causes a syntax error

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#33]
The following tl code causes a syntax error:
```lua
local printfn: function(string, number, number): nil
```
If I remove the `nil` return value at the end, the error is gone.

Is this a bug?

**Comment by hishamhm** [comment]
> Is this a bug?

Yes, I think this should be allowed. Should be an easy fix:

```diff
diff --git a/tl.lua b/tl.lua
index 36c7061..376a866 100644
--- a/tl.lua
+++ b/tl.lua
@@ -1025,6 +1025,7 @@ end
 parse_type = function(tokens, i, errs)
    if tokens[i].tk == "string" or
       tokens[i].tk == "boolean" or
+      tokens[i].tk == "nil" or
       tokens[i].tk == "number" then
       return i + 1, {
          ["y"] = tokens[i].y,
diff --git a/tl.tl b/tl.tl
index 4e6d032..39e0d83 100644
--- a/tl.tl
+++ b/tl.tl
@@ -1025,6 +1025,7 @@ end
 parse_type = function(tokens: {Token}, i: number, errs: {ParseError}): number, Type, number
    if tokens[i].tk == "string"
       or tokens[i].tk == "boolean"
+      or tokens[i].tk == "nil"
       or tokens[i].tk == "number" then
       return i + 1, {
          y = tokens[i].y,
```

I will add this plus a regression test.

In the meantime, you can use

```lua
local printfn: function(string, number, number): ()
```

(you can use parentheses to disambiguate multiple returns and an empty `()` works to indicate return with arity 0)

**Comment by hishamhm** [comment]
Actually, `()` is more correct if your function returns nothing, because in Lua `return` and `return nil` are technically different:

```lua
> print(select('#', (function() return end)() ))
0
> print(select('#', (function() return nil end)() ))
1
```

This difference is actually observable in some C API functions which check the number of arguments explicitly. This works:

```
> function returns_nil() return nil end
> table.insert({}, returns_nil() )
```

This fails:

```
> function returns_nothing() return end
> table.insert({}, returns_nothing() )
stdin:1: wrong number of arguments to 'insert'
stack traceback:
	[C]: in function 'table.insert'
	stdin:1: in main chunk
	[C]: in ?
```

Currently, tl does not catch the above (even after fixing it to accept `nil` in the return type), because it assumes that every type accepts `nil` and that any missing argument can be read as `nil`. This is not true for `table.insert`, which accepts `table.insert({}, nil)` but fails with `table.insert({})`. tl will need some special feature for "explicit arguments" if we want to detect that.

However, tl is able to catch this distinction:

```
local ok = returns_nil() -- accepts, ok is nil
local ok = returns_nothing() -- fails, ok doesn't get a type
```

**Comment by pdesaulniers** [comment]
Ah, I wasn't aware of this. Thanks for the explanation!
