### ISSUE TITLE
Function overloading in record definitions

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#36]
Some functions in LÖVE have multiple overloads. For instance, [love.graphics.print](https://love2d.org/wiki/love.graphics.print).

Right now, it seems like tl only checks the last overload:
```lua
global love_graphics = record
	print: function(text: string, x: number, y: number, r: number, sx: number, sy: number, ox: number, oy: number, kx: number, ky:number)
	print: function(coloredtext: {any}, x: number, y: number, r: number, sx: number, sy: number, ox: number, oy: number, kx: number, ky:number)
end

global love = record
	graphics: love_graphics
end
```
```lua
require("love")

function love.draw()
	love.graphics.print("Hello lol", 100, 100)
end
```
```
main.tl:4:22: argument 1: got string "Hello lol", expected {any}
```
(In this specific example, perhaps a union type would've been better)

**Comment by hishamhm** [comment]
This needs an intersection type (`t1 & t2` in TypeScript). tl actually _has_ some internal support for it, because I use it precisely to declare function overloads in the standard library (see `poly` in `tl.tl` -- yes, I'm cheating by inventing a type I'm not making available to users!)

I guess I will have to make it visible to users sooner rather than later! I might initially restrict it to function declarations, which is how I'm using `poly` internally. The syntax you tried above for function overloading in a record could actually work nicely for that, to prevent users from assuming they can intersect any type with any other type.

**Comment by hishamhm** [comment]
Please give this a try!
https://github.com/hishamhm/tl/pull/38

**Comment by hishamhm** [comment]
@pdesaulniers did #38 work for your purposes?

**Comment by pdesaulniers** [comment]
@hishamhm I haven't tested it that much yet, but it does appear to work!
