### ISSUE TITLE
No type-checking on boolean arguments?

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#44]
tl does not detect an error in this code:

```lua
local function abc(x: boolean)

end

abc("(✿◠‿◠)")
abc(123)
abc({})
```

Is this a bug?

**Comment by hishamhm** [comment]
Currently, this is [on purpose](https://github.com/hishamhm/tl/blob/v0.1.0/tl.tl#L3724): every Lua value can be used in a boolean context because nil is falsy and all other values are truthy, so tl accepts them as booleans (except in equality comparisons, where they are usually bugs, because doing things like `x == true` where `x` is not a boolean is always `false`).

It might be a good idea to make this stricter, especially in .tl ("strict") mode and keep the current behavior for .lua files...

**Comment by pdesaulniers** [comment]
Yeah, I think the check should be stricter for function arguments. Otherwise, it could be a source of bugs.

I think this kind of usage is fine, though:
```lua
local x: string = x or "Hello"
```
or
```lua
if x then
    -- ...
end
```

**Comment by hishamhm** [comment]
@pdesaulniers How does #46 look?

**Comment by pdesaulniers** [comment]
Looks great! Works as expected :)
