### ISSUE TITLE
Add documentation for creating and testing development builds

### ISSUE THREAD

**Issue by ash-nolan** [hishamhm/tl#51]
Creating and testing edits to `tl.tl` feels a bit awkward because changing `tl` itself requires bootstrapping from a "working" version of `tl` It would be nice if some documentation could be added describing how one should edit `tl.tl` and regenerate `tl.lua`  and/run the test suite in a single shell command.

As someone not particularly familiar with Lua or or the luarocks  build system it was a bit difficult getting a development environment up and running for edits.

**Comment by hishamhm** [comment]
> Creating and testing edits to tl.tl feels a bit awkward because changing tl itself requires bootstrapping from a "working" version of tl

That is true. The magic incantation is `git checkout tl.lua`, which restores the generated `tl.lua` to the one committed in the repo (which is, supposedly, one that is known to work).

When dealing with a bootstrapped project, one has to always be careful to not make the code itself depend on a new feature when implementing it (otherwise you get into a chicken-and-egg situation).

I'll keep this issue open to remind me to make a note about this when writing some developer docs, thanks for the feedback!

**Comment by hishamhm** [comment]
@ash-nolan I added a basic development guide! Thank you for providing inspiration for it via this issue!

https://github.com/hishamhm/tl/blob/master/docs/developing.md
