### ISSUE TITLE
[Q] differences from Andre's Typed Lua

### ISSUE THREAD

**Issue by ildar** [hishamhm/tl#65]
(this may go into documentation later) 
What are the key differences and similarities with Typed Lua developed by Andre which is now live in Titan and its forks? 

Related: https://github.com/hishamhm/tl/issues/24

**Comment by hishamhm** [comment]
Since André's Typed Lua is not an active project, I don't think it's worth to keep a comparison in tl's official docs for two reasons: (1) a comparison to an inactive project will have diminishing relevance over time, and (2) tl is still changing quite a bit, so maintaining a comparison page is extra work as things might get more or less similar to Typed Lua's original design over time.

For anyone wishing to go through the details, I recommend reading [André's thesis](https://github.com/andremm/typedlua/raw/master/doc/thesis/thesis_andre_certified.pdf).

Titan (which isn't active either) and Pallene (which is) were influenced by Typed Lua's design but were not a strict continuation of it either. At some point it might be useful to add a comparison to Pallene, perhaps, but right now I don't think it's worth it since both projects are in flux (reason (2) above applies to both projects — hard to write down and maintain a comparison between two moving targets).

I think the most useful comparison is about their goals, which I think #24 does a good job at summarizing. Perhaps that comment in that issue should be part of the official docs?

**Comment by ildar** [comment]
I see
My note about including into docs isn't important. I just wanted to know
how TL is better and what it lacks in comparison with TypedLua.

Also I see that both TL and Pallene lack the community place (chat). That's
sad.
Thanks!

**Comment by andremm** [comment]
> What are the key differences and similarities with Typed Lua developed by Andre which is now live in Titan and its forks?

I'm sorry if Typed Lua's `README.md` gave the impression that it was living inside Titan and Pallene, which is not the case and it is gracefully explained in #24. For this reason, I went there and updated the `README.md` for removing the Titan reference, which was misleading and outdated anyway.

**Comment by resolritter** [comment]
> Perhaps that comment in that issue should be part of the official docs?

I'd say yes. Since it's an immature language still, people will naturally want to discover (1) why it exists, (2) why is it useful and (3) what are your personal motivations for creating this new project (i.e. what did not work in prior art and prompted your action). I think that comment does a good job in covering those three questions.

Lua folks might have more interesting in comparing it to Pallene or whatever else, but that didn't matter for me personally as I wasn't coming from this sort of background; regardless, your post was still informative for me for the reasons I mentioned above.

**Comment by hishamhm** [comment]
>>     Perhaps that comment in that issue should be part of the official docs?
>
> I'd say yes.

I created #70 which moves that comment into `docs/` :+1:
