### ISSUE TITLE
point the place of "unknown variables"

### ISSUE THREAD

**Issue by ildar** [hishamhm/tl#74]
Currently TL just shows the plain list of "unknown variables".
It may be valuable to know if it is:
1. a toplevel variable
2. an argument of a toplevel function
3. inside a function.

**Comment by hishamhm** [comment]
Instead of describing the place where the unknown variable occurs, I found it more valuable to print the exact location (in line, column position of the file):

```
========================================
4 unknown variables:
bla.lua:2:8: a
bla.lua:3:11: b
bla.lua:5:7: hello
bla.lua:5:13: world
```

I'm afraid it would take a bunch of extra context tracking in the type checker to add the info you suggest, but with editor integration highlighting these tokens in context, I suppose the location would be sufficient without having to add complexity to the compiler itself.

So I'm choosing to not add this for now, but thanks for the feedback!
